// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_iulW4CrXnjPe5P5pVLDV7HcMJneQtvY',
    appId: '1:639146379622:web:98aa843c4d3fd0492f20a7',
    messagingSenderId: '639146379622',
    projectId: 'userdata-c1abf',
    authDomain: 'userdata-c1abf.firebaseapp.com',
    storageBucket: 'userdata-c1abf.firebasestorage.app',
    measurementId: 'G-ZYMK72Z6QG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_Ae_CeCr8bAJtcDVLuvjS5-Qy-DS1G84',
    appId: '1:639146379622:android:2e574889ff5caf672f20a7',
    messagingSenderId: '639146379622',
    projectId: 'userdata-c1abf',
    storageBucket: 'userdata-c1abf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-e022-TtJr3l5UkxQEcvWlVuCUvAVNXo',
    appId: '1:639146379622:ios:6dd03963242db9a22f20a7',
    messagingSenderId: '639146379622',
    projectId: 'userdata-c1abf',
    storageBucket: 'userdata-c1abf.firebasestorage.app',
    iosBundleId: 'com.example.userDataFirestore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-e022-TtJr3l5UkxQEcvWlVuCUvAVNXo',
    appId: '1:639146379622:ios:6dd03963242db9a22f20a7',
    messagingSenderId: '639146379622',
    projectId: 'userdata-c1abf',
    storageBucket: 'userdata-c1abf.firebasestorage.app',
    iosBundleId: 'com.example.userDataFirestore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_iulW4CrXnjPe5P5pVLDV7HcMJneQtvY',
    appId: '1:639146379622:web:1f1a6f162e2cc0fc2f20a7',
    messagingSenderId: '639146379622',
    projectId: 'userdata-c1abf',
    authDomain: 'userdata-c1abf.firebaseapp.com',
    storageBucket: 'userdata-c1abf.firebasestorage.app',
    measurementId: 'G-Q5SZZ237RJ',
  );
}
